### ISSUE TITLE
アイコンに使用する画像の有効範囲を自由に調整できるようにする

### ISSUE THREAD

**Issue by NONAKA-Yuuki** [NONAKA-Yuuki/NS_Profile_Generator#6]
現状のアイコン画像は、アップロードされた画像をそのまま正円に切り取っている（長方形の場合、長辺を直径として切り取る）仕様となっている為、アイコンで使いたい部分だけを正方形に切り抜いた画像を先に用意しておく必要がある。

しかし、実際問題そんなことするのは面倒なので、下記のようなオペレーションに変更したい。

1. 画像をアップロード
2. ポップアップが出現し、アップロードした画像と丸枠を表示
3. アイコンで使いたい部分だけを丸枠に収めるようにして、完了であればOKを押す
4. 調整したサイズ、場所で切り抜きをした画像をプレビューに表示

ポップアップ出してブラウザ上で画像を拡大したり、画像の好きな位置で丸く切り抜けるようにできれば誰もが直感的かつ痒いところに手が届くサービスにできると思っているので実装希望

**Comment by NONAKA-Yuuki** [comment]
これ参考にする：https://zihuatanejo.blog/archives/1021

**Comment by NONAKA-Yuki** [comment]
機能実装できたのでクローズ
